// frontend/src/components/forms/CreateSongForm.vue
<template>
  <form class="grid create-song-form" @submit="handleSubmit">
    <div class="card-title">Добавить песню</div>
    <input class="input" placeholder="Название" v-model="form.title" required />
    <input
      class="input"
      placeholder="Исполнитель"
      v-model="form.artist"
      required
    />
    <textarea
      class="textarea"
      placeholder="Описание"
      v-model="form.description"
    />
    <div class="create-song-form__link-row">
      <input
        class="input"
        placeholder="Ссылка"
        v-model="form.linkUrl"
        required
      />
      <select class="select" v-model.number="form.linkKind">
        <option :value="1">YouTube</option>
        <option :value="2">Яндекс Музыка</option>
        <option :value="3">Soundcloud</option>
      </select>
    </div>
    <input
      class="input"
      placeholder="Роли через запятую"
      v-model="form.roles"
    />
    <label v-if="canFeature" class="create-song-form__checkbox">
      <input type="checkbox" v-model="form.featured" />
      Сделать featured
    </label>
    <button class="button" type="submit" :disabled="isSaving">
      {{ isSaving ? "Сохраняем…" : "Создать" }}
    </button>
    <div v-if="error" class="create-song-form__error">{{ error }}</div>
  </form>
</template>

<script setup>
import { reactive, ref } from "vue";
import "../../styles/domains/songs.css";

const props = defineProps({
  canFeature: { type: Boolean, default: false },
  onSubmit: { type: Function, required: true },
});

const form = reactive({
  title: "",
  artist: "",
  description: "",
  linkUrl: "",
  linkKind: 1,
  roles: "вокал, гитара, бас, барабаны",
  thumbnailUrl: "",
  featured: false,
});
const isSaving = ref(false);
const error = ref(null);

const handleSubmit = async (event) => {
  event.preventDefault();
  isSaving.value = true;
  error.value = null;
  try {
    await props.onSubmit({
      title: form.title,
      artist: form.artist,
      description: form.description,
      linkUrl: form.linkUrl,
      linkKind: form.linkKind,
      roles: form.roles
        .split(",")
        .map((r) => r.trim())
        .filter(Boolean),
      thumbnailUrl: form.thumbnailUrl,
      featured: props.canFeature ? form.featured : undefined,
    });
    form.title = "";
    form.artist = "";
    form.description = "";
    form.linkUrl = "";
    form.thumbnailUrl = "";
    form.featured = false;
  } catch (err) {
    error.value = err.message;
  } finally {
    isSaving.value = false;
  }
};
</script>

// frontend/src/components/forms/CreateSongForm.tsx
import { useState } from "react";
import type { FormEvent } from "react";
import type { SongLinkType } from "../../proto/song_pb";
import "../../styles/components/create-song-form.css";

type Props = {
	onSubmit: (payload: {
		title: string;
		artist: string;
		description?: string;
		linkUrl: string;
		linkKind: SongLinkType;
		roles: string[];
		thumbnailUrl?: string;
		featured?: boolean;
	}) => Promise<void>;
	canFeature?: boolean;
};

const CreateSongForm = ({ onSubmit, canFeature }: Props) => {
	const [form, setForm] = useState({
		title: "",
		artist: "",
		description: "",
		linkUrl: "",
		linkKind: 1 as SongLinkType,
		roles: "вокал, гитара, бас, барабаны",
		thumbnailUrl: "",
		featured: false,
	});
	const [isSaving, setIsSaving] = useState(false);
	const [error, setError] = useState<string | null>(null);

	const handleSubmit = async (e: FormEvent) => {
		e.preventDefault();
		setIsSaving(true);
		setError(null);
		try {
			await onSubmit({
				title: form.title,
				artist: form.artist,
				description: form.description,
				linkUrl: form.linkUrl,
				linkKind: form.linkKind,
				roles: form.roles.split(",").map((r) => r.trim()).filter(Boolean),
				thumbnailUrl: form.thumbnailUrl,
				featured: canFeature ? form.featured : undefined,
			});
			setForm({ ...form, title: "", artist: "", description: "", linkUrl: "", thumbnailUrl: "", featured: false });
		} catch (err) {
			setError((err as Error).message);
		} finally {
			setIsSaving(false);
		}
	};

	return (
		<form className="grid create-song-form" onSubmit={handleSubmit}>
			<div className="card-title">Добавить песню</div>
			<input className="input" placeholder="Название" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required />
			<input className="input" placeholder="Исполнитель" value={form.artist} onChange={(e) => setForm({ ...form, artist: e.target.value })} required />
			<textarea
				className="textarea"
				placeholder="Описание"
				value={form.description}
				onChange={(e) => setForm({ ...form, description: e.target.value })}
			/>
			<div className="create-song-form__link-row">
				<input className="input" placeholder="Ссылка" value={form.linkUrl} onChange={(e) => setForm({ ...form, linkUrl: e.target.value })} required />
				<select
					className="select"
					value={form.linkKind}
					onChange={(e) => setForm({ ...form, linkKind: Number(e.target.value) as SongLinkType })}
				>
					<option value={1}>YouTube</option>
					<option value={2}>Яндекс Музыка</option>
					<option value={3}>Soundcloud</option>
				</select>
			</div>
			<input
				className="input"
				placeholder="Роли через запятую"
				value={form.roles}
				onChange={(e) => setForm({ ...form, roles: e.target.value })}
			/>
			{canFeature && (
				<label className="create-song-form__checkbox">
					<input
						type="checkbox"
						checked={form.featured}
						onChange={(e) => setForm({ ...form, featured: e.target.checked })}
					/>
					Сделать featured
				</label>
			)}
			<button className="button" type="submit" disabled={isSaving}>
				{isSaving ? "Сохраняем…" : "Создать"}
			</button>
			{error && <div className="create-song-form__error">{error}</div>}
		</form>
	);
};

export default CreateSongForm;
